# Generated by Django 5.2.7 on 2025-10-24 18:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('interes', 'Interés'), ('reserva', 'Reserva'), ('confirmada', 'Venta confirmada'), ('cancelada', 'Cancelada')], default='interes', max_length=20)),
                ('nota', models.TextField(blank=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intenciones', to='clientes.cliente')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intenciones', to='lotes.lote')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
