# Generated by Django 5.2.7 on 2025-10-24 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('estado', models.CharField(choices=[('interesado', 'Interesado'), ('visito', 'Visitó'), ('reservo', 'Reservó'), ('compro', 'Compró'), ('desistio', 'Desistió'), ('mora', 'En mora')], default='interesado', max_length=20)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
