# Generated by Django 5.2.7 on 2025-10-24 18:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=20)),
                ('superficie_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('vendido', 'Vendido'), ('mora', 'En mora'), ('liberado', 'Liberado')], default='disponible', max_length=20)),
                ('ubicacion_textual', models.CharField(blank=True, max_length=255)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='lotes.proyecto')),
            ],
            options={
                'ordering': ['proyecto', 'codigo'],
                'unique_together': {('proyecto', 'codigo')},
            },
        ),
    ]
